from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column


class IntIdPkMixin:
    """
    Mixin that provides a standard integer primary key field named `id`.

    This mixin is used across all database models to ensure consistency in
    primary key definitions. The field is automatically configured as a
    primary key and typically serves as the unique identifier for each record.

    Fields:
        id — integer primary key, automatically generated by the database.

    Notes:
        - Ensures that all entities share a consistent primary key type.
        - Used in combination with the project's Base class and other mixins.
    """
    id: Mapped[int] = mapped_column(primary_key=True)